### PR TITLE
Fix incorrect plural "Objects" for all FindGameObjectWithTag references

### PR DESCRIPTION
**Pull request by jlmakes**
Hey @oferei, this is a simple typo fix for all 4 of the snippets, per language. :bow:

### CODE REVIEW

**Comment by oferei** [comment]
hey, thanks for the help, but this fix is not perfect. apparently Unity now has two methods: FindObjectOfType and FindObjectsOfType. this wasn't the case in Unity v5.1.0, so it's time to update the package. however, removing FindObjectsOfType (plural) is not right, as this function will exists.

anyway, this package is generated using a process that starts with the [crawler](https://github.com/oferei/unity-scripting-crawler) that gathers data from the web documentation and then continues with the [generator](https://github.com/oferei/sublime-unity-completions-generator) which formats the data for Sublime. so modifying this package manually is useless - any fixes should be done to one of the other projects. please wait until I run the process again for Unity 5.3 and see if that fixes everything. if not, please report an issue.

**Comment by oferei** [comment]
correction: I mentioned <i>FindObjectOfType</i> when you talked about <i>FindGameObjectWithTag</i>. well, now I'm a bit confused, because <i>FindGameObjectWithTag</i> (singular) seems to work, although it is undocumented.

**Comment by jlmakes** [comment]
You‘re right it isn’t documented.

Admittedly, I was following along with a Unity tutorial that used it which was where I learned it. When later using it in my project and your completions package in Sublime, it autocompleted to the plural version and my code broke… so I assumed it was a bug.

I see now it's actually the documented method, and I could have fixed my code by accessing the first item in the list. Either way, I look forward to the Unity 5.3 update. :bow:

**Comment by oferei** [comment]
coming soon. I may also add the undocumented methods.

**Comment by oferei** [comment]
enjoy v5.3.1

**Comment by jlmakes** [comment]
:beers:

**Pull request closed without merging**
